/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto3;

import java.io.BufferedReader;
import java.io.FileReader;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.StringTokenizer;
import org.graphstream.graph.*;
import org.graphstream.graph.implementations.*;
import org.graphstream.algorithm.Dijkstra;
import org.graphstream.graph.Edge;
import org.graphstream.graph.Graph;
import org.graphstream.graph.Node;
import org.graphstream.graph.Path;
import org.graphstream.graph.implementations.SingleGraph;
import java.util.List;

/**
 *
 * @author alex
 */
public class main extends javax.swing.JFrame {

    /**
     * Creates new form main
     */
    Graph graph = new SingleGraph("tutorial 1");

    public main() {
        initComponents();
        initComponents();
        this.setLocationRelativeTo(this);
        graph.setStrict(false);
        graph.setAutoCreate(true);

        try {
            String s1;
            String s2;
            String p1 = null, p2 = null;
            BufferedReader br = new BufferedReader(new FileReader("gente.txt"));

            while ((s1 = br.readLine()) != null) {
                int numTokens = 0;
                StringTokenizer st = new StringTokenizer(s1, ",");

                while (st.hasMoreTokens()) {
                    s2 = st.nextToken();
                    numTokens++;
                    if (p1 == null) {
                        p1 = s2;
                    } else {
                        p2 = s2;
                    }
                }
                graph.addEdge(p1 + p2, p1, p2, true);
                p1 = null;
                p2 = null;
            }
            br.close();
        } catch (Exception e) { //Catch de excepciones
            System.err.println("Ocurrio un error: " + e.getMessage());
        }

        for (Node node : graph) {
            node.addAttribute("ui.label", node.getId());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        verificar_amigo = new javax.swing.JDialog();
        jLabel2 = new javax.swing.JLabel();
        amigos_salir = new javax.swing.JButton();
        buscar_amistad = new javax.swing.JButton();
        son_amigos = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        box2 = new javax.swing.JComboBox<>();
        box1 = new javax.swing.JComboBox<>();
        conexion_amigo = new javax.swing.JDialog();
        jLabel3 = new javax.swing.JLabel();
        amigos_salir1 = new javax.swing.JButton();
        conectar = new javax.swing.JButton();
        conexion = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        box_conectar2 = new javax.swing.JComboBox<>();
        box_conectar1 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jLabel2.setText("AMISTADES");

        amigos_salir.setText("SALIR");
        amigos_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                amigos_salirActionPerformed(evt);
            }
        });

        buscar_amistad.setText("AMIGOS?");
        buscar_amistad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscar_amistadActionPerformed(evt);
            }
        });

        son_amigos.setText("      ---");

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        javax.swing.GroupLayout verificar_amigoLayout = new javax.swing.GroupLayout(verificar_amigo.getContentPane());
        verificar_amigo.getContentPane().setLayout(verificar_amigoLayout);
        verificar_amigoLayout.setHorizontalGroup(
            verificar_amigoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(verificar_amigoLayout.createSequentialGroup()
                .addGroup(verificar_amigoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(verificar_amigoLayout.createSequentialGroup()
                        .addGap(173, 173, 173)
                        .addComponent(buscar_amistad))
                    .addGroup(verificar_amigoLayout.createSequentialGroup()
                        .addGap(190, 190, 190)
                        .addComponent(jLabel2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, verificar_amigoLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(verificar_amigoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, verificar_amigoLayout.createSequentialGroup()
                        .addComponent(amigos_salir)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, verificar_amigoLayout.createSequentialGroup()
                        .addComponent(box1, 0, 150, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(box2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(75, 75, 75))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, verificar_amigoLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(189, 189, 189))
            .addGroup(verificar_amigoLayout.createSequentialGroup()
                .addGap(186, 186, 186)
                .addComponent(son_amigos, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        verificar_amigoLayout.setVerticalGroup(
            verificar_amigoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(verificar_amigoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(amigos_salir)
                .addGap(26, 26, 26)
                .addComponent(jLabel2)
                .addGroup(verificar_amigoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(verificar_amigoLayout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addGroup(verificar_amigoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(box2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(box1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(66, 66, 66))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, verificar_amigoLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(57, 57, 57)))
                .addComponent(buscar_amistad)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(son_amigos)
                .addContainerGap())
        );

        jLabel3.setText("Conectar amigos");

        amigos_salir1.setText("SALIR");
        amigos_salir1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                amigos_salir1ActionPerformed(evt);
            }
        });

        conectar.setText("conectar");
        conectar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                conectarActionPerformed(evt);
            }
        });

        conexion.setText("                                                             ---");

        jSeparator4.setOrientation(javax.swing.SwingConstants.VERTICAL);

        javax.swing.GroupLayout conexion_amigoLayout = new javax.swing.GroupLayout(conexion_amigo.getContentPane());
        conexion_amigo.getContentPane().setLayout(conexion_amigoLayout);
        conexion_amigoLayout.setHorizontalGroup(
            conexion_amigoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, conexion_amigoLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(conexion_amigoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, conexion_amigoLayout.createSequentialGroup()
                        .addComponent(amigos_salir1)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, conexion_amigoLayout.createSequentialGroup()
                        .addComponent(box_conectar1, 0, 150, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(box_conectar2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(75, 75, 75))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, conexion_amigoLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(189, 189, 189))
            .addGroup(conexion_amigoLayout.createSequentialGroup()
                .addGroup(conexion_amigoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(conexion_amigoLayout.createSequentialGroup()
                        .addGap(173, 173, 173)
                        .addComponent(conectar))
                    .addGroup(conexion_amigoLayout.createSequentialGroup()
                        .addGap(171, 171, 171)
                        .addComponent(jLabel3)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(conexion_amigoLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(conexion, javax.swing.GroupLayout.PREFERRED_SIZE, 416, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        conexion_amigoLayout.setVerticalGroup(
            conexion_amigoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(conexion_amigoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(amigos_salir1)
                .addGap(56, 56, 56)
                .addComponent(jLabel3)
                .addGroup(conexion_amigoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(conexion_amigoLayout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(conexion_amigoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(box_conectar2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(box_conectar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(66, 66, 66))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, conexion_amigoLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(57, 57, 57)))
                .addComponent(conectar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(conexion)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Ver si existe amistades");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Ver conexion entre personas");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Ver grafo");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel1.setText("Proyecto 3");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addComponent(jButton2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(147, 147, 147)
                        .addComponent(jButton3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(157, 157, 157)
                        .addComponent(jLabel1)))
                .addContainerGap(123, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jLabel1)
                .addGap(30, 30, 30)
                .addComponent(jButton3)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addContainerGap(99, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here: 
        graph.display();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        for (Node e : graph.getEachNode()) {
            box1.addItem(e.getId());
            box2.addItem(e.getId());
        }
        this.setVisible(false);
        verificar_amigo.setSize(500, 400);
        verificar_amigo.setLocationRelativeTo(this);
        verificar_amigo.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void amigos_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_amigos_salirActionPerformed
        // TODO add your handling code here:
        verificar_amigo.setVisible(false);
        son_amigos.setText("");
        this.setVisible(true);
    }//GEN-LAST:event_amigos_salirActionPerformed

    private void buscar_amistadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscar_amistadActionPerformed
        // TODO add your handling code here:
        boolean amistad = false;
        for (Edge e : graph.getEachEdge()) {
            if (e.getId().equals(box1.getSelectedItem().toString() + box2.getSelectedItem().toString())) {
                son_amigos.setText("SI");
                amistad = true;
            }
        }
        if (amistad == false) {
            son_amigos.setText("NO");
        }
    }//GEN-LAST:event_buscar_amistadActionPerformed

    private void amigos_salir1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_amigos_salir1ActionPerformed
        // TODO add your handling code here:
        conexion_amigo.setVisible(false);
        conexion.setText("");
        this.setVisible(true);
    }//GEN-LAST:event_amigos_salir1ActionPerformed

    private void conectarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_conectarActionPerformed
        // TODO add your handling code here:

        String inicio=box_conectar1.getSelectedItem().toString(),fin=box_conectar2.getSelectedItem().toString();
        Dijkstra dijkstra = new Dijkstra(Dijkstra.Element.EDGE, null, "length");

        dijkstra.init(graph);
        dijkstra.setSource(graph.getNode(inicio));
        dijkstra.compute();

        List<Node> list1 = new ArrayList<Node>();
        for (Node node : dijkstra.getPathNodes(graph.getNode(fin))) {
            list1.add(0, node);
        }

        List<Node> list2 = dijkstra.getPath(graph.getNode(fin)).getNodePath();

        dijkstra.clear();

        dijkstra = new Dijkstra(Dijkstra.Element.NODE, null, null);
        dijkstra.init(graph);
        dijkstra.setSource(graph.getNode(inicio));
        dijkstra.compute();

        Iterator<Path> pathIterator = dijkstra.getAllPathsIterator(graph.getNode(fin));
        while (pathIterator.hasNext()) {
            conexion.setText(pathIterator.next().toString());
        }
    }//GEN-LAST:event_conectarActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        for (Node e : graph.getEachNode()) {
            box_conectar1.addItem(e.getId());
            box_conectar2.addItem(e.getId());
        }

        this.setVisible(false);
        conexion_amigo.setSize(500, 400);
        conexion_amigo.setLocationRelativeTo(this);
        conexion_amigo.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton amigos_salir;
    private javax.swing.JButton amigos_salir1;
    private javax.swing.JComboBox<String> box1;
    private javax.swing.JComboBox<String> box2;
    private javax.swing.JComboBox<String> box_conectar1;
    private javax.swing.JComboBox<String> box_conectar2;
    private javax.swing.JButton buscar_amistad;
    private javax.swing.JButton conectar;
    private javax.swing.JLabel conexion;
    private javax.swing.JDialog conexion_amigo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JLabel son_amigos;
    private javax.swing.JDialog verificar_amigo;
    // End of variables declaration//GEN-END:variables
}
